# Generated by Django 2.2.7 on 2019-11-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191119_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='/media/images/Tifizza.png', null=True, upload_to='images/'),
        ),
    ]
