# Generated by Django 2.2.7 on 2019-11-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191120_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='/images/Tifizza.png', null=True, upload_to='images/'),
        ),
    ]
