# Generated by Django 2.2.7 on 2019-11-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20191120_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='/images/Tiffiza.png', null=True, upload_to='images/'),
        ),
    ]
